
# 1. 기본 이미지를 설정합니다. Java 17을 기반으로 사용
FROM openjdk:17-jdk-alpine

# 2. 빌드 아규먼트 (Build Arguments) 정의
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG JWT_SECRET
ARG REQ_ADDRESS
ARG CLOUDINARY_NAME
ARG CLOUDINARY_KEY
ARG CLOUDINARY_SECRET

# 3. 이 빌드 아규먼트들을 환경 변수로 설정
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV MAIL_HOST=$MAIL_HOST
ENV MAIL_PORT=$MAIL_PORT
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV REQ_ADDRESS=$REQ_ADDRESS
ENV CLOUDINARY_NAME=$CLOUDINARY_NAME
ENV CLOUDINARY_KEY=$CLOUDINARY_KEY
ENV CLOUDINARY_SECRET=$CLOUDINARY_SECRET

# 4. 애플리케이션 jar 파일을 빌드 결과에서 복사
COPY build/libs/myapp.jar /app/molly-0.0.1-SNAPSHOT.jar
EXPOSE 8080
# 5. 애플리케이션 실행 명령어
ENTRYPOINT ["java", "-jar", "/app/molly-0.0.1-SNAPSHOT.jar"]