FROM openjdk:17-jdk-alpine

ARG SPRING_DATASOURCE_URL\
    SPRING_DATASOURCE_USERNAME\
    SPRING_DATASOURCE_PASSWORD\
    MAIL_HOST\
    MAIL_PORT\
    MAIL_USERNAME\
    MAIL_PASSWORD\
    JWT_SECRET\
    REQ_ADDRESS\
    CLOUDINARY_NAME\
    CLOUDINARY_KEY\
    CLOUDINARY_SECRET

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL\
    SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME\
    SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD\
    MAIL_HOST=$MAIL_HOST\
    MAIL_PORT=$MAIL_PORT\
    MAIL_USERNAME=$MAIL_USERNAME\
    MAIL_PASSWORD=$MAIL_PASSWORD\
    JWT_SECRET=$JWT_SECRET\
    REQ_ADDRESS=$REQ_ADDRESS\
    CLOUDINARY_NAME=$CLOUDINARY_NAME\
    CLOUDINARY_KEY=$CLOUDINARY_KEY\
    CLOUDINARY_SECRET=$CLOUDINARY_SECRET

ARG JAR_FILE=build/libs/*-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]